// Generate tiny base64 blur placeholders so full-bleed photos (and the cota
// overlay) never start drawing over a blank box. Run: node scripts/blur.mjs
import sharp from "sharp";
import { writeFileSync } from "node:fs";

const images = [
  "/hero/poster.jpg",
  "/projetos/sicredi-centro-sul.jpg",
  "/projetos/sicredi-acacias-sinop.jpeg",
  "/projetos/sicredi-canarana.jpg",
  "/projetos/sede-celeiro.jpg",
  "/projetos/agencia-agro-lucas.jpeg",
  "/time/foto_joao.jpg",
];

const out = {};
for (const p of images) {
  const buf = await sharp("public" + p)
    .resize(24)
    .jpeg({ quality: 45 })
    .toBuffer();
  out[p] = `data:image/jpeg;base64,${buf.toString("base64")}`;
}

writeFileSync(
  "lib/blur.ts",
  `// AUTO-GENERATED by scripts/blur.mjs — do not edit by hand.\nexport const blur: Record<string, string> = ${JSON.stringify(
    out,
    null,
    2,
  )};\n\nexport const blurFor = (src: string) => blur[src];\n`,
);
console.log("wrote lib/blur.ts", Object.keys(out).length, "entries");
